# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Schier
tagline:          'None'
description:      'Coding for fun'
url:              http://www.erikschierboom.com

author:
  name:           'Erik Schierboom'
  url:            https://twitter.com/erikschierboom

paginate:         5

exclude:          ['run.sh', 'run-drafts.sh']