# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Schier
tagline:          'None'
description:      'Coding for fun'
url:              http://www.erikschierboom.com
encoding:         UTF-8

author:
  name:           'Erik Schierboom'
  url:            https://twitter.com/erikschierboom

paginate:         5

exclude:          ['*.sh', 'node_modules', 'bower_components', 'package.json', 'tsd.json', 'bower.json', 'Gruntfile.js', 
                   'LICENSE.md', 'README.md', 'CNAME', 'Gemfile', 'Gemfile.lock']